In [2]:
import numpy as np
import pandas as pd
import sklearn as sk

In [3]:
df = pd.read_csv(r"C:\Users\jemin\Downloads\Datamites\trainRF.csv")

df

,battery_power,blue,clock_speed,dual_sim,fc,four_g,int_memory,m_dep,mobile_wt,n_cores,...,px_height,px_width,ram,sc_h,sc_w,talk_time,three_g,touch_screen,wifi,price_range
0,842,0,2.2,0,1,0,7,0.6,188,2,...,20,756,2549,9,7,19,0,0,1,1
1,1021,1,0.5,1,0,1,53,0.7,136,3,...,905,1988,2631,17,3,7,1,1,0,2
2,563,1,0.5,1,2,1,41,0.9,145,5,...,1263,1716,2603,11,2,9,1,1,0,2
3,615,1,2.5,0,0,0,10,0.8,131,6,...,1216,1786,2769,16,8,11,1,0,0,2
4,1821,1,1.2,0,13,1,44,0.6,141,2,...,1208,1212,1411,8,2,15,1,1,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,794,1,0.5,1,0,1,2,0.8,106,6,...,1222,1890,668,13,4,19,1,1,0,0
1996,1965,1,2.6,1,0,0,39,0.2,187,4,...,915,1965,2032,11,10,16,1,1,1,2
1997,1911,0,0.9,1,1,1,36,0.7,108,8,...,868,1632,3057,9,1,5,1,1,0,3
1998,1512,0,0.9,0,4,1,46,0.1,145,5,...,336,670,869,18,10,19,1,1,1,0
1999,510,1,2.0,1,5,1,45,0.9,168,6,...,483,754,3919,19,4,2,1,1,1,3

In [6]:
#1 Display phones where ram is greater than 3000 and battery_power is greater than 1500.

show = df.loc[(df['ram'] > 3000) & (df['battery_power'] > 1500)]

show

,battery_power,blue,clock_speed,dual_sim,fc,four_g,int_memory,m_dep,mobile_wt,n_cores,...,px_height,px_width,ram,sc_h,sc_w,talk_time,three_g,touch_screen,wifi,price_range
6,1821,0,1.7,0,4,1,10,0.8,139,8,...,381,1018,3220,13,8,18,1,0,1,3
11,1520,1,2.2,0,5,1,33,0.5,177,8,...,151,1005,3826,14,9,13,1,1,1,3
21,1709,1,2.1,0,1,0,13,1.0,156,2,...,974,1385,3283,17,1,15,1,0,0,3
30,1579,1,0.5,1,0,0,5,0.2,88,7,...,1358,1739,3532,17,11,12,0,0,1,3
37,1725,1,1.6,1,6,1,6,0.5,119,2,...,609,1307,3429,6,5,4,1,1,0,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1955,1515,1,2.1,1,4,1,24,0.9,176,5,...,747,1247,3104,6,5,20,1,0,0,3
1957,1589,0,0.6,0,0,0,5,0.8,112,5,...,776,1397,3430,7,5,19,1,1,1,3
1985,1829,1,2.1,0,8,0,59,0.1,91,5,...,1457,1919,3142,16,6,5,1,1,1,3
1991,1882,0,2.0,0,11,1,44,0.8,113,8,...,4,743,3579,19,8,20,1,1,0,3
1997,1911,0,0.9,1,1,1,36,0.7,108,8,...,868,1632,3057,9,1,5,1,1,0,3

In [7]:
#2 Calculate the average value of the ram column. 

avg = df['ram'].mean()

avg

np.float64(2124.213)

In [8]:
#3 Count how many phones belong to each price_range category. 

count = df['price_range'].value_counts()

count

price_range
1    500
2    500
3    500
0    500
Name: count, dtype: int64

In [11]:
#4 Identify the maximum RAM value and display the row of the phone with that value. 

max = df.loc[df['ram'] == df['ram'].max()]

max

,battery_power,blue,clock_speed,dual_sim,fc,four_g,int_memory,m_dep,mobile_wt,n_cores,...,px_height,px_width,ram,sc_h,sc_w,talk_time,three_g,touch_screen,wifi,price_range
940,1456,0,1.6,1,9,1,39,0.1,80,8,...,815,1666,3998,6,3,13,1,1,0,3

In [12]:
#5 Display all unique values in price_range and count how many unique categories exist. 

uniq = df['price_range'].unique()

count = df['price_range'].nunique()

print(uniq)
print(count)

[1 2 3 0]
4

In [14]:
#6 Count missing values in the ram, battery_power, and int_memory columns. 

miss = df[['ram','battery_power','int_memory']].isnull().sum()

print(miss)

ram              0
battery_power    0
int_memory       0
dtype: int64

In [16]:
#7 Count the duplicate rows in the dataset. Do not remove them. 

dup = df.duplicated().sum()

dup

np.int64(0)

In [19]:
#8 Calculate the average ram for each price_range category. 

avg = df.groupby('price_range')['ram'].mean()

avg

price_range
0     785.314
1    1679.490
2    2582.816
3    3449.232
Name: ram, dtype: float64

In [20]:
#9 Create X using ram, battery_power, and int_memory. Create y using price_range. Print both shapes. 

x = df[['ram','battery_power','int_memory']]
y = df['price_range']

print(x.shape)
print(y.shape)

(2000, 3)
(2000,)

In [23]:
#10 Filter phones where price_range is 3. Display the number of matching phones and their average RAM. 

show = df.loc[df['price_range'] == 3]

count = show.shape[0]
avg_ram = show['ram'].mean()

print("Number of phones:", count)
print("Average RAM:", avg_ram)

Number of phones: 500
Average RAM: 3449.232